global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'hospital-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hospital-core:8080']

  - job_name: 'postgres-db'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]